### ISSUE TITLE
getWebhooks - Error sending from Guilded to Discord

### ISSUE THREAD

**Issue by VIRUXE** [fuwwy/guilded-bridge#2]
I'm having this issue:
```
/root/guilded-bridge/discord.js:48
        const webhook = (await channel.getWebhooks()).find(w => w.application_id == this.client.user.id) || (await channel.createWebhook({
                                       ^

TypeError: Cannot read properties of undefined (reading 'getWebhooks')
    at DiscordToGuildedBridge.sendToWebhook (/root/guilded-bridge/discord.js:48:40)
    at GuildedToDiscordBridge.translateToDiscord (/root/guilded-bridge/guilded.js:82:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.7.0
``` 
Maybe this is related to permissions but my bot has Administrator perms so that should be enough.

**Comment by VIRUXE** [comment]
Managed to trace this error back to trying to access inexistent channels on the other side, instead of just sending messages to the default channel.

**Comment by VIRUXE** [comment]
Found an actual error. Will send PR later.
