### ISSUE TITLE
Error with starting bridge

### ISSUE THREAD

**Issue by raymand211092** [fuwwy/guilded-bridge#4]
/root/guilded-bridge/node_modules/@guildedjs/guilded.js/dist/structures/Base.js:12
        this.id = data.id.toString();
                       ^

TypeError: Cannot read properties of undefined (reading 'id')
    at new Base (/root/guilded-bridge/node_modules/@guildedjs/guilded.js/dist/structures/Base.js:12:24)
    at new User (/root/guilded-bridge/node_modules/@guildedjs/guilded.js/dist/structures/User.js:20:9)
    at new ClientUser (/root/guilded-bridge/node_modules/@guildedjs/guilded.js/dist/structures/Client.js:178:9)
    at Client.<anonymous> (/root/guilded-bridge/node_modules/@guildedjs/guilded.js/dist/structures/Client.js:109:25)
    at Generator.next (<anonymous>)
    at fulfilled (/root/guilded-bridge/node_modules/@guildedjs/guilded.js/dist/structures/Client.js:5:58

**Comment by PeterStindberg** [comment]
Duplicate to https://github.com/itsfolf/guilded-bridge/issues/5

**Comment by PeterStindberg** [comment]
same
