### ISSUE TITLE
Error starting the bridge

### ISSUE THREAD

**Issue by eveee00** [fuwwy/guilded-bridge#5]
`> guilded-bridge@1.0.0 start
> node index.js

X:\Desktop\guilded-bridge\node_modules\@guildedjs\guilded.js\dist\structures\Base.js:12
        this.id = data.id.toString();
                       ^

TypeError: Cannot read properties of undefined (reading 'id')
    at new Base (X:\Desktop\guilded-bridge\node_modules\@guildedjs\guilded.js\dist\structures\Base.js:12:24)
    at new User (X:\Desktop\guilded-bridge\node_modules\@guildedjs\guilded.js\dist\structures\User.js:20:9)
    at new ClientUser (X:\Desktop\guilded-bridge\node_modules\@guildedjs\guilded.js\dist\structures\Client.js:178:9)
    at Client.<anonymous> (X:\Desktop\guilded-bridge\node_modules\@guildedjs\guilded.js\dist\structures\Client.js:109:25)
    at Generator.next (<anonymous>)
    at fulfilled (X:\Desktop\guilded-bridge\node_modules\@guildedjs\guilded.js\dist\structures\Client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.1
`

**Comment by coolpeter98** [comment]
same error

**Comment by PeterStindberg** [comment]
same

**Comment by PeterStindberg** [comment]
Duplicate to https://github.com/itsfolf/guilded-bridge/issues/4
